[package]
name = "circuitlab"
version = "0.1.0"
description = "Integrated EDA + electronics simulation suite"
authors = ["CircuitLab"]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "circuitlab_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rfd = "0.14"

[features]
# This feature is used for production builds or when a dev server is not specified.
custom-protocol = ["tauri/custom-protocol"]
